DROP TABLE IF EXISTS TRANSACTIONS;
DROP TYPE IF EXISTS TRANSACTION_TYPE;
DROP TABLE IF EXISTS GRANTED_SHARE_RECORDS;
DROP TABLE IF EXISTS RECORDS;
DROP TABLE IF EXISTS USERS;
DROP TYPE IF EXISTS USER_TYPE;