CREATE TYPE USER_TYPE AS ENUM ('officer', 'student', 'employer');
CREATE TABLE IF NOT EXISTS USERS (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  hashedpassword VARCHAR(255) NOT NULL,
  role USER_TYPE NOT NULL DEFAULT 'employer',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS RECORDS (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  holder UUID NOT NULL REFERENCES USERS(ID),
  gpax FLOAT(2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS GRANTED_SHARE_RECORDS (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  record UUID NOT NULL REFERENCES RECORDS(ID),
  viewer UUID NOT NULL REFERENCES USERS(ID),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TYPE TRANSACTION_TYPE AS ENUM ('insert', 'update', 'delete');
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  type TRANSACTION_TYPE NOT NULL DEFAULT 'insert',
  record UUID NOT NULL REFERENCES RECORDS(ID),
  issuer UUID NOT NULL REFERENCES USERS(ID),
  issued_data TIMESTAMPTZ NOT NULL DEFAULT NOW()
);